# Generated by Django 3.1.13 on 2021-08-13 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mls_id', models.IntegerField(blank=True, null=True)),
                ('listing_url', models.URLField(blank=True, max_length=2000)),
                ('agent_notes', models.TextField(blank=True)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('zip_code', models.CharField(blank=True, max_length=12)),
                ('country', models.CharField(blank=True, default='USA', max_length=3)),
                ('state', models.CharField(blank=True, max_length=14)),
                ('status', models.CharField(blank=True, default='Open', max_length=40)),
                ('escrow_status', models.CharField(blank=True, default='Unpaid', max_length=40)),
                ('down_payment_status', models.CharField(blank=True, default='Unpaid', max_length=40)),
                ('mutually_executed_contract_date', models.DateField(blank=True, default=None, null=True, verbose_name='MEC Date')),
                ('down_payment_deadline', models.DateField(blank=True, default=None, null=True)),
                ('down_payment_dest', models.CharField(blank=True, max_length=200)),
                ('down_payment_stripe_confirmation_id', models.CharField(blank=True, max_length=200)),
                ('down_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('escrow_deadline', models.DateField(blank=True, default=None, null=True)),
                ('escrow_payment_dest', models.CharField(blank=True, max_length=200)),
                ('escrow_stripe_confirmation_id', models.CharField(blank=True, max_length=200)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('magic_url_seed', models.CharField(blank=True, max_length=22)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared', models.BooleanField(default=False)),
                ('document_file', models.FileField(upload_to='documents/orders/')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
        ),
    ]
